#
# This is a basic workflow to help you get started with Actions

name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
    
jobs:
    ros2:
                            runs-on: ubuntu-20.04

                            steps:

                            - name: Checkout
                              uses: actions/checkout@v2
                              with:
                                repository: ${{ env.REPO }}
                                ref: ${{ github.job }}

                            - name: Setup ROS
                              uses: ros-tooling/setup-ros@v0.1

                            - name: Get Source Code
                              run: mkdir src && vcs import src < autoware.proj.repos

                            - name: Set up Docker Buildx
                              uses: docker/setup-buildx-action@v1

                            # - name: Login to GitHub Container Registry
                            #   uses: docker/login-action@v1
                            #   with:
                            #     registry: ghcr.io
                            #     username: ${{ github.repository_owner }}
                            #     password: ${{ secrets.GHCR_TOKEN }}

                            - name: Creat Dockerfile
                              run: |
                                    cat << EOF > Dockerfile
                                    FROM alpine
                                    LABEL org.opencontainers.image.source https://github.com/${{ env.REPO }}
                                    COPY . /AutowareArchitectureProposal

                                    EOF
                            - name: Build and push
                              run: |
                                    docker buildx build --output "type=image,push=true" --tag ros2 --platform linux/amd64,linux/arm64 --file ./Dockerfile .

