#
# This is a basic workflow to help you get started with Actions

name: CI



# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # - name: Setup ROS 2
      #   uses:  ros-tooling/setup-ros@0.1.2
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO }}
          ref: ${{ github.job }}
      
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GHCR_TOKEN }}

    - name: Creat Dockerfile
      run: |
            cat << EOF > Dockerfile
            FROM alpine
            LABEL org.opencontainers.image.source https://github.com/${{ env.REPO }}
            COPY . /AutowareArchitectureProposal
            EOF
    - name: Build and push
      run: |
            docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ env.IMG_NAME }}:${{ github.job }} \
            --file ./Dockerfile .






      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # Runs a single command using the runners shell




#   env:
#   REPO: ${{ github.repository_owner }}/AutowareArchitectureProposal
#   IMG_NAME: ghcr.io/${{ github.repository_owner }}/autoware-architecture-proposal

# jobs:
#   ros2:
#     runs-on: ubuntu-20.04

#     steps:

#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         repository: ${{ env.REPO }}
#         ref: ${{ github.job }}

#     - name: Setup ROS
#       uses: ros-tooling/setup-ros@v0.1

#     - name: Get Source Code
#       run: mkdir src && vcs import src < autoware.proj.repos

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v1
#       with:
#         registry: ghcr.io
#         username: ${{ github.repository_owner }}
#         password: ${{ secrets.GHCR_TOKEN }}

#     - name: Creat Dockerfile
#       run: |
#             cat << EOF > Dockerfile
#             FROM alpine
#             LABEL org.opencontainers.image.source https://github.com/${{ env.REPO }}
#             COPY . /AutowareArchitectureProposal
#             EOF
#     - name: Build and push
#       run: |
#             docker buildx build \
#             --output "type=image,push=true" \
#             --platform linux/amd64,linux/arm64 \
#             --tag ${{ env.IMG_NAME }}:${{ github.job }} \
#             --file ./Dockerfile .
