#
# This is a basic workflow to help you get started with Actions

name: CI



# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container:
      image: ubuntu:bionic
    env:
                 ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prerequest
        uses: actions/setup-python@v2
  
      - name: Setup ROS 2
        uses:  ros-tooling/setup-ros@0.1.2
        
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Build up 
        run: colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release 
        






      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # Runs a single command using the runners shell
